const validateRules = {
  require: '必填',
  // isNotEmpty: '不能为空',
  email: '邮箱',
  mobile: '手机号',
  idCard: '身份证',
  checkPassword: '密码',
  number: '数字',
  integer: '整数',
  isPositiveInteger: '正整数',
  float: '浮点数',
  date: '日期',
  url: '链接',
  alpha: '纯字母',
  alphaNum: '字母和数字',
  alphaDash: '字母和数字，下划线_及破折号-',
  chs: '汉字',
  chsAlpha: '汉字和字母',
  chsAlphaNum: '汉字、字母和数字',
  chsDash: '汉字、字母、数字和下划线_及破折号-',
  lower: '小写字符',
  upper: '大写字符',
  checkIDArray: '整数型数字数组',
  checkSwitch: '开关',
  activeUrl: '有效的域名或者IP',
  macAddr: 'MAC地址',
  zip: '邮政编码',
  boolean: '布尔值',
  array: '数组'
}

export default validateRules
